<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-5B3SDIE" failures="1" tests="2" name="Personal Loan" time="0.046" errors="0" timestamp="2024-11-05T16:30:04 EST">
  <testcase classname="test.day1" name="demo1" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.demo1(day1.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- demo1 -->
  <testcase classname="test.day2" name="demo2" time="0.001"/>
  <testcase classname="test.day1" name="demo" time="0.0">
    <ignored/>
  </testcase> <!-- demo -->
</testsuite> <!-- Personal Loan -->
